<?php
/**
 * @file
 * Integration of the Infusion User Interface Options with Drupal.
 */

/**
 * Implements hook_help().
 */
function infusion_uio_help($path, $arg) {
  switch ($path) {
    case 'admin/help#infusion_uio': {
        $uiohelp = '<h3>' . t('About') . '</h3>';
        $uiohelp .= '<p>' . t('The Infusion User Interface Options module integrates the Infusion UIO component with Drupal.') . '</p>';
        $uiohelp .= '<p>' . t('Infusion\'s UI Options component allows users to personalize interfaces and content to meet individual needs and preferences.') . '</p>';
        $uiohelp .= '<p>' . t('It currently has the following features:') . '<ul>';
        $uiohelp .= '<li>' . t('Text Size') . '</li>';
        $uiohelp .= '<li>' . t('Text Style') . '</li>';
        $uiohelp .= '<li>' . t('Line Spacing') . '</li>';
        $uiohelp .= '<li>' . t('Colour and Contrast') . '</li>';
        $uiohelp .= '<li>' . t('Display Table of Contents') . '</li>';
        $uiohelp .= '<li>' . t('Emphasize Links') . '</li></ul></p>';
        return $uiohelp;
        break;
      }
  }
}

/**
 * Implements hook_menu().
 */
function infusion_uio_menu() {
  // Admin config page.
  $items['admin/config/user-interface/infusion-uio'] = array(
    'title' => 'Infusion UI Options settings',
    'description' => 'Configure Infusion User Interface Options',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('infusion_ui_settings_form'),
  );
  
  return $items;
}

/**
 * Implements hook_form().
 */
function infusion_ui_settings_form($node, &$form_state) {
  
  $uio_options = array(t('Fat Panel Options'), t('Full Page'), t('Full Page With Preview'));
  $form['infusion_uio_interface'] = array(
    '#type' => 'radios',
    '#title' => t('Select the default UIO interface'),
    '#default_value' => variable_get('infusion_uio_interface', 'Fat Panel Options'),
    '#options' => drupal_map_assoc($uio_options),
  );
  $form['btn_text'] = array(
    '#type' => 'fieldset',
    '#title' => t('Custom Show/Hide Button Text'),
    '#description' => t('Customize the Show/Hide button for your UIO'),
    '#collapsible' => 'TRUE',
    '#collapsed' => 'TRUE',
  );
  $form['btn_text']['infusion_uio_show_btn'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get('infusion_uio_show_btn', 'Preferences'),
    '#maxlength' => 128,
    '#required' => TRUE,
    '#title' => t('Show Button'),
    '#description' => t('Enter a custom text for the \'Show\' button'),
  );
    $form['btn_text']['infusion_uio_hide_btn'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get('infusion_uio_hide_btn', 'Preferences'),
    '#maxlength' => 128,
    '#required' => TRUE,
    '#title' => t('Hide Button'),
    '#description' => t('Enter a custom text for the \'Hide\' button'),
  );
  return system_settings_form($form);
}